openapi: 3.0.1
info:
  title: User management
  version: 1.0.0
servers:
  - url: https://hq1.appsflyer.com/api/user-management/v1.0
security:
  - bearerAuth: []
paths:
  /users: {}
  /users/{userIds}: {}
  /roles: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        **Important: API V2 Token Revocation**


        All API V2 tokens generated before March 10, 2026, 19:00 UTC have been
        revoked. If your token was generated before this date, please regenerate
        it. [Learn
        how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).


        Authorization HTTP header containing API V2 token (bearer token) is
        required.

         The admin [gets the V2 token in the dashboard](https://support.appsflyer.com/hc/en-us/articles/360004562377)
